export type PageId =
  | 'home'
  | 'game'
  | 'practice'
  | 'practiceGame'
  | 'visualLab'
  | 'atlas'
  | 'quiz'
  | 'onboarding'
  | 'interpreter'
  | 'sentenceLab'
  | 'achievements'
  | 'mistakeReview'
  | 'finalChallenge'
  | 'profile'
  | 'myProgress'
  | 'about';
